# Generated by Django 2.1.3 on 2019-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TICKs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('product_code', models.CharField(max_length=50)),
                ('tick_id', models.CharField(max_length=50)),
                ('best_ask', models.CharField(max_length=50)),
                ('best_ask_size', models.CharField(max_length=50)),
                ('best_bid', models.CharField(max_length=50)),
                ('best_bid_size', models.CharField(max_length=50)),
                ('total_ask_depth', models.CharField(max_length=50)),
                ('total_bid_depth', models.CharField(max_length=50)),
                ('ltp', models.CharField(max_length=50)),
                ('volume', models.SmallIntegerField()),
                ('volume_by_product', models.CharField(max_length=50)),
            ],
        ),
    ]
